/**
 * Tests for the Tor Browser (Firefox ESR) build generated by tools/build_tor.js.
 * Verifies the manifest transforms, background script transform, verbatim
 * copies, and that the committed tor/ tree is in sync with the source.
 */
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const ROOT = path.resolve(__dirname, '..');
const TOR = path.join(ROOT, 'tor');
const { buildManifest, buildBackgroundJs, buildTree, GECKO_ID } = require('../tools/build_tor.js');

test('Tor build - manifest uses background.scripts instead of service_worker', () => {
  const manifest = JSON.parse(buildManifest(fs.readFileSync(path.join(ROOT, 'manifest.json'), 'utf8')));

  assert.ok(!manifest.background.service_worker, 'no service_worker (unsupported in Firefox MV3)');
  assert.deepEqual(manifest.background.scripts, ['src/storage/Storage.js', 'background.js'],
    'Storage.js must load before background.js (no importScripts in event pages)');
});

test('Tor build - manifest uses options_ui and gecko settings', () => {
  const manifest = JSON.parse(buildManifest(fs.readFileSync(path.join(ROOT, 'manifest.json'), 'utf8')));

  assert.ok(!manifest.options_page, 'options_page is Chrome-only');
  assert.equal(manifest.options_ui.page, 'dashboard/dashboard.html');
  assert.equal(manifest.options_ui.open_in_tab, true);

  assert.equal(manifest.browser_specific_settings.gecko.id, GECKO_ID);
  assert.ok(manifest.browser_specific_settings.gecko.strict_min_version, 'min version set for Tor Browser ESR');

  // Everything else must be preserved from the Chrome manifest.
  const chrome = JSON.parse(fs.readFileSync(path.join(ROOT, 'manifest.json'), 'utf8'));
  assert.deepEqual(manifest.permissions, chrome.permissions);
  assert.deepEqual(manifest.host_permissions, chrome.host_permissions);
  assert.deepEqual(manifest.content_scripts, chrome.content_scripts);
  assert.equal(manifest.devtools_page, chrome.devtools_page);
});

test('Tor build - background.js has importScripts removed and stays valid JS', () => {
  const src = fs.readFileSync(path.join(ROOT, 'background.js'), 'utf8');
  const out = buildBackgroundJs(src);

  assert.ok(!out.includes('importScripts('), 'importScripts must be stripped');
  assert.ok(out.includes('chrome.contextMenus.create'), 'rest of the logic preserved');
  // Must parse as valid JavaScript.
  assert.doesNotThrow(() => new Function(out.replace(/^\/\* AUTO-GENERATED[^\n]*\n/, '')));
});

test('Tor build - copied app files are byte-identical to the Chrome tree', () => {
  const tree = buildTree();
  for (const rel of ['dashboard/dashboard.js', 'src/engine/ScraperEngine.js', 'lib/i18n.js', 'content/selector_picker.js', 'popup/popup.js']) {
    assert.ok(tree.has(rel), `${rel} present in tor build`);
    assert.ok(tree.get(rel).equals(fs.readFileSync(path.join(ROOT, rel))), `${rel} is byte-identical`);
  }
  assert.ok(tree.has('README.md'), 'tor build ships its own README with install steps');
});

test('Tor build - committed tor/ folder is up to date (check mode passes)', () => {
  assert.ok(fs.existsSync(path.join(TOR, 'manifest.json')), 'tor/ folder exists');
  // --check exits non-zero when stale; execFileSync throws in that case.
  assert.doesNotThrow(() => {
    execFileSync(process.execPath, [path.join(ROOT, 'tools', 'build_tor.js'), '--check'], { stdio: 'pipe' });
  }, 'tor/ must be regenerated after source changes (npm run build:tor)');
});
