/**
 * P4.12 (part 3) — tor hash denetimi (snapshot test).
 *
 * tor/HASHES.json is generated by tools/build_tor.js and lists the SHA-256
 * of every file in tor/ (except the manifest itself). This test re-hashes
 * the committed tree and verifies it matches — replacing manual inspection
 * with a committed, diffable snapshot. Any drift (source edit without a
 * rebuild, hand-edited artifact, partial sync) fails loudly.
 */
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { execFileSync } = require('node:child_process');

const ROOT = path.resolve(__dirname, '..');
const TOR = path.join(ROOT, 'tor');

function listFiles(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...listFiles(full).map((p) => path.join(entry.name, p)));
    else out.push(entry.name);
  }
  return out.sort();
}

test('P4.12 - tor/HASHES.json matches the committed tor/ tree (snapshot)', () => {
  const manifestPath = path.join(TOR, 'HASHES.json');
  assert.ok(fs.existsSync(manifestPath), 'tor/HASHES.json must be committed (run npm run build:tor)');
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  assert.equal(manifest.generatedBy, 'tools/build_tor.js');

  const listed = new Set(manifest.files.map((f) => f.path));
  const onDisk = listFiles(TOR).filter((rel) => rel !== 'HASHES.json');
  const onDiskSet = new Set(onDisk);

  // No orphan files on disk, no missing files in the manifest.
  for (const rel of onDisk) assert.ok(listed.has(rel), `tor/${rel} exists on disk but is missing from HASHES.json`);
  for (const rel of listed) assert.ok(onDiskSet.has(rel), `HASHES.json lists tor/${rel} but it does not exist`);
  assert.equal(manifest.fileCount, onDisk.length, 'fileCount matches the tree');

  // Every hash must match the real file content.
  for (const entry of manifest.files) {
    const actual = crypto.createHash('sha256').update(fs.readFileSync(path.join(TOR, entry.path))).digest('hex');
    assert.equal(actual, entry.sha256, `hash mismatch for tor/${entry.path}`);
  }
});

test('P4.12 - npm run check:tor passes on the committed tree', () => {
  // The anchored-build check regenerates the expected tree (including the
  // hash manifest) from chrome-edge/ sources and compares byte-for-byte.
  execFileSync(process.execPath, ['tools/build_tor.js', '--check'], { cwd: ROOT, stdio: 'pipe' });
});
