/**
 * Tests for the Tor Browser (Firefox ESR) NATIVE build generated by
 * tools/build_tor.js. The tor/ tree targets only Firefox/Tor: promise-based
 * browser.* APIs with async/await and no chrome.* calls at all.
 */
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'chrome-edge');
const TOR = path.join(ROOT, 'tor');
const { buildManifest, buildTree, GECKO_ID } = require('../tools/build_tor.js');

test('Tor build - manifest uses background.scripts instead of service_worker', () => {
  const manifest = JSON.parse(buildManifest(fs.readFileSync(path.join(SRC, 'manifest.json'), 'utf8')));

  assert.ok(!manifest.background.service_worker, 'no service_worker (unsupported in Firefox MV3)');
  assert.deepEqual(manifest.background.scripts, ['src/storage/Storage.js', 'background.js'],
    'Storage.js must load before background.js (event page has no importScripts)');
});

test('Tor build - manifest uses options_ui and gecko settings', () => {
  const manifest = JSON.parse(buildManifest(fs.readFileSync(path.join(SRC, 'manifest.json'), 'utf8')));

  assert.ok(!manifest.options_page, 'options_page is Chrome-only');
  assert.equal(manifest.options_ui.page, 'dashboard/dashboard.html');
  assert.equal(manifest.options_ui.open_in_tab, true);

  assert.equal(manifest.browser_specific_settings.gecko.id, GECKO_ID);
  assert.ok(manifest.browser_specific_settings.gecko.strict_min_version, 'min version set for Tor Browser ESR');

  // Everything else must be preserved from the Chrome manifest.
  const chrome = JSON.parse(fs.readFileSync(path.join(SRC, 'manifest.json'), 'utf8'));
  assert.deepEqual(manifest.permissions, chrome.permissions);
  assert.deepEqual(manifest.host_permissions, chrome.host_permissions);
  assert.deepEqual(manifest.content_scripts, chrome.content_scripts);
  assert.equal(manifest.devtools_page, chrome.devtools_page);
});

test('Tor build - no chrome.* API call anywhere in the generated JS', () => {
  const tree = buildTree();
  for (const [rel, content] of tree) {
    if (!rel.endsWith('.js')) continue;
    const text = content.toString('utf8');
    // Tight pattern: identifiers like chromeEl, strings like 'chrome://' and
    // prose such as "slideshow chrome. The" must not trip the check.
    assert.ok(!/(?<![A-Za-z0-9_$])chrome\.[A-Za-z_$]/.test(text),
      `${rel} must not call the chrome.* API in the Firefox-native build`);
  }
});

test('Tor build - generated JS files are syntactically valid', () => {
  const vm = require('node:vm');
  const tree = buildTree();
  for (const [rel, content] of tree) {
    if (!rel.endsWith('.js')) continue;
    // vm.Script parses (compiles) without executing — a SyntaxError throws.
    assert.doesNotThrow(() => new vm.Script(content.toString('utf8'), { filename: rel }),
      `${rel} must parse as valid JavaScript`);
  }
});

test('Tor build - native background is a browser.* event page', () => {
  const tree = buildTree();
  const bg = tree.get('background.js').toString('utf8');

  assert.ok(!bg.includes('importScripts('), 'no worker-style imports in an event page');
  assert.match(bg, /browser\.runtime\.onInstalled\.addListener/);
  assert.match(bg, /browser\.contextMenus\.create/);
  assert.match(bg, /return Promise\.resolve\(\{ success: true \}\)/,
    'message listener answers by returning a Promise (native Firefox pattern)');
});

test('Tor build - dashboard picker & runner are async browser.* code', () => {
  const tree = buildTree();
  const dash = tree.get(path.join('dashboard', 'dashboard.js')).toString('utf8');

  assert.match(dash, /async function getTargetTabId\(\)/, 'getTargetTabId is promise-based');
  assert.match(dash, /async function ensureHostPermission\(\)/, 'permission gate is promise-based');
  assert.match(dash, /async function launchElementPicker\(/, 'picker is async');
  assert.match(dash, /await browser\.scripting\.executeScript/, 'injection awaited');
  assert.match(dash, /await browser\.tabs\.create\(\{ url: url, active: false \}\)/, 'tab runner awaited');
  assert.match(dash, /const permitted = await ensureHostPermission\(\);/, 'startScraping awaits the async gate');
  // The runner must keep the standalone fetch fallback for non-extension use.
  assert.match(dash, /Default fetch & DOMParser fallback/);
});

test('Tor build - storage uses awaited browser.storage.local', () => {
  const tree = buildTree();
  const storage = tree.get(path.join('src', 'storage', 'Storage.js')).toString('utf8');

  assert.match(storage, /await browser\.storage\.local\.get/);
  assert.match(storage, /await browser\.storage\.local\.set/);
  assert.match(storage, /await browser\.storage\.local\.remove/);
  assert.match(storage, /isExtensionStorage/, 'honest naming in the Firefox build');
  assert.ok(!storage.includes('isChromeStorage'), 'Chrome-flavoured names are gone');
  // IndexedDB / localStorage fallbacks must survive for standalone mode.
  assert.match(storage, /_rawGetAllSitemapsIDB/);
});

test('Tor build - content scripts answer messages by returning Promises', () => {
  const tree = buildTree();
  const picker = tree.get(path.join('content', 'selector_picker.js')).toString('utf8');
  const scraper = tree.get(path.join('content', 'scraper_content.js')).toString('utf8');

  assert.match(picker, /browser\.runtime\.onMessage\.addListener/);
  assert.match(picker, /return Promise\.resolve\(\{ success: true \}\)/);
  assert.ok(!picker.includes('sendResponse'), 'no callback-style sendResponse in the native build');
  assert.match(scraper, /browser\.runtime\.onMessage\.addListener/);
  assert.ok(!scraper.includes('sendResponse'), 'scraper content answers via returned Promise');
});

test('Tor build - devtools page registers the panel with absolute paths', () => {
  const tree = buildTree();
  const devtools = tree.get(path.join('devtools', 'devtools.js')).toString('utf8');

  assert.match(devtools, /browser\.devtools\.panels\.create/);
  assert.match(devtools, /'\/devtools\/panel\.html'/, 'root-absolute page path (Firefox resolves relative paths wrongly)');
  assert.match(devtools, /'\/icons\/icon32\.png'/, 'root-absolute icon path');
});

test('Tor build - engines, locales and markup stay identical to the root tree', () => {
  const tree = buildTree();
  for (const rel of [
    'src/engine/ScraperEngine.js', 'src/engine/SelectorEngine.js', 'src/models/Sitemap.js',
    'lib/csv.js', 'dashboard/dashboard.html', 'devtools/panel.html',
    path.join('_locales', 'en', 'messages.json')
  ]) {
    const key = rel.split('/').join(path.sep);
    assert.ok(tree.has(key), `${rel} present in tor build`);
    assert.ok(tree.get(key).equals(fs.readFileSync(path.join(SRC, rel))), `${rel} is byte-identical`);
  }
  assert.ok(tree.has('README.md'), 'tor build ships its own README with install steps');
});

test('Tor build - committed tor/ folder is up to date (check mode passes)', () => {
  assert.ok(fs.existsSync(path.join(TOR, 'manifest.json')), 'tor/ folder exists');
  // --check exits non-zero when stale; execFileSync throws in that case.
  assert.doesNotThrow(() => {
    execFileSync(process.execPath, [path.join(ROOT, 'tools', 'build_tor.js'), '--check'], { stdio: 'pipe' });
  }, 'tor/ must be regenerated after source changes (npm run build:tor)');
});
