/* AUTO-GENERATED by tools/build_tor.js — Firefox/Tor native (browser.*) build. Do not edit directly. */
/**
 * Web Scraper Scraping Execution Content Script.
 * Handles DOM extractions, dynamic clicking (load more/tabs), and infinite scrolling.
 */
(function () {
  'use strict';

  if (window.__webScraperContentLoaded) {
    return;
  }
  window.__webScraperContentLoaded = true;

  async function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, Math.max(0, ms)));
  }

  async function handleClickSelector(selectorConfig) {
    const clickSelector = selectorConfig.clickElementSelector;
    if (!clickSelector) {
      // Empty click selector: querySelectorAll('') would throw a SyntaxError
      // on every page of the crawl — treat it as "no clicks to perform".
      return { clicksDone: 0, initialMarked: 0 };
    }
    const clickType = selectorConfig.clickType || 'clickMore';
    const clickDelay = selectorConfig.clickDelay || 1000;
    // Hard safety cap: the dashboard can lower it per selector, but never
    // above this ceiling (a runaway "load more" loop would hang the crawl).
    const maxClicks = Math.min(parseInt(selectorConfig.maxClicks, 10) || 50, 200);

    // "Discard initial elements" support: before any click lands, tag every
    // record-container element that ALREADY exists in the DOM. The engine
    // (with options.discardInitialElements) then drops the tagged elements
    // and keeps only the content the clicks actually loaded. Marking happens
    // here — the page's own JavaScript — because the dashboard only sees the
    // post-click DOM.
    let initialMarked = 0;
    if (selectorConfig.discardInitialElements === true) {
      const initialSelectors = Array.isArray(selectorConfig.initialSelectors)
        ? selectorConfig.initialSelectors
        : [];
      for (const css of initialSelectors) {
        if (!css) continue;
        try {
          document.querySelectorAll(css).forEach((el) => {
            if (!el.hasAttribute('data-ws-initial')) {
              el.setAttribute('data-ws-initial', '1');
              initialMarked++;
            }
          });
        } catch (e) {
          // Invalid container selector — skip it, keep clicking.
        }
      }
    }

    let clickCount = 0;
    const clickedElements = new Set();

    while (clickCount < maxClicks) {
      const buttons = Array.from(document.querySelectorAll(clickSelector)).filter(b => {
        return b.offsetParent !== null && !clickedElements.has(b);
      });

      if (buttons.length === 0) break;

      const targetBtn = buttons[0];
      clickedElements.add(targetBtn);

      targetBtn.scrollIntoView({ behavior: 'smooth', block: 'center' });
      await sleep(100);

      // Dispatch real click events
      targetBtn.dispatchEvent(new MouseEvent('mousedown', { bubbles: true }));
      targetBtn.dispatchEvent(new MouseEvent('mouseup', { bubbles: true }));
      targetBtn.click();

      clickCount++;
      await sleep(clickDelay);

      if (clickType === 'clickOnce') {
        break;
      }
    }

    return { clicksDone: clickCount, initialMarked: initialMarked };
  }

  async function handleScrollSelector(selectorConfig) {
    const scrollDelay = selectorConfig.scrollDelay || 1000;
    const maxScrolls = selectorConfig.maxScrolls || 20;
    const scrollSelector = selectorConfig.scrollElementSelector;

    const scrollTarget = scrollSelector ? document.querySelector(scrollSelector) : null;
    let scrollsDone = 0;
    let lastHeight = 0;

    while (scrollsDone < maxScrolls) {
      if (scrollTarget) {
        lastHeight = scrollTarget.scrollHeight;
        scrollTarget.scrollTop = scrollTarget.scrollHeight;
      } else {
        lastHeight = document.documentElement.scrollHeight;
        window.scrollTo(0, document.documentElement.scrollHeight);
      }

      scrollsDone++;
      await sleep(scrollDelay);

      const newHeight = scrollTarget ? scrollTarget.scrollHeight : document.documentElement.scrollHeight;
      if (newHeight <= lastHeight) {
        // No more new content loaded
        break;
      }
    }

    return { scrollsDone: scrollsDone };
  }

  // Listen for execution commands from the dashboard/background. Returning
  // a Promise from the listener is the native Firefox async-response path.
  if (typeof browser !== 'undefined' && browser.runtime && browser.runtime.onMessage) {
    browser.runtime.onMessage.addListener((request) => {
      if (request.type === 'EXECUTE_PAGE_ACTIONS') {
        return (async () => {
          try {
            if (request.actions && request.actions.click) {
              await handleClickSelector(request.actions.click);
            }
            if (request.actions && request.actions.scroll) {
              await handleScrollSelector(request.actions.scroll);
            }
            return { success: true };
          } catch (err) {
            return { success: false, error: err.message };
          }
        })();
      }
    });
  }
})();
