/* AUTO-GENERATED by tools/build_tor.js — Firefox/Tor native (browser.*) build. Do not edit directly. */
/**
 * Web Scraper Scraping Execution Content Script.
 * Handles DOM extractions, dynamic clicking (load more/tabs), and infinite scrolling.
 */
(function () {
  'use strict';

  if (window.__webScraperContentLoaded) {
    return;
  }
  window.__webScraperContentLoaded = true;

  async function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, Math.max(0, ms)));
  }

  /**
   * Minimal CSS path for an element — the `uniqueCSSSelector` identity used by
   * clickElementUniquenessType. Walks up to the nearest meaningful id.
   */
  function cssPathFor(el) {
    const parts = [];
    let cur = el;
    while (cur && cur.nodeType === 1 && cur !== document.documentElement) {
      const tag = cur.tagName.toLowerCase();
      if (cur.id) {
        parts.unshift(`${tag}#${cur.id}`);
        break;
      }
      let part = tag;
      const parent = cur.parentElement;
      if (parent) {
        const sameTag = Array.from(parent.children).filter((c) => c.tagName === cur.tagName);
        if (sameTag.length > 1) part += `:nth-of-type(${sameTag.indexOf(cur) + 1})`;
      }
      parts.unshift(part);
      cur = parent;
    }
    return parts.join(' > ');
  }

  /**
   * Identity of a click target according to the selector's
   * `clickElementUniquenessType` (uniqueText | uniqueHTMLText | uniqueCSSSelector
   * | uniqueHTML).
   *
   * Element IDENTITY is not usable here: frameworks routinely REPLACE the
   * "load more" node on every click, so a Set of element references either
   * lets the same logical button be clicked forever, or — when the node is
   * stable — makes the second pass find "nothing left to click" and stop
   * after a single click. That was the clickMore bug this replaces. The
   * option was persisted, exported and imported but never actually read.
   */
  function uniquenessSignature(el, type) {
    const text = ((el.innerText || el.textContent || '') + '').replace(/\s+/g, ' ').trim();
    switch (type) {
      case 'uniqueText':
        return text;
      case 'uniqueHTML':
        return el.outerHTML || '';
      case 'uniqueCSSSelector':
        return cssPathFor(el);
      case 'uniqueHTMLText':
      default:
        return `${text}\u0000${el.innerHTML || ''}`;
    }
  }

  async function handleClickSelector(selectorConfig) {
    const clickSelector = selectorConfig.clickElementSelector;
    if (!clickSelector) {
      // Empty click selector: querySelectorAll('') would throw a SyntaxError
      // on every page of the crawl — treat it as "no clicks to perform".
      return { clicksDone: 0, initialMarked: 0 };
    }
    const clickType = selectorConfig.clickType || 'clickMore';
    const clickDelay = selectorConfig.clickDelay || 1000;
    const uniquenessType = selectorConfig.clickElementUniquenessType || 'uniqueHTMLText';
    // Hard safety cap: the dashboard can lower it per selector, but never
    // above this ceiling (a runaway "load more" loop would hang the crawl).
    const maxClicks = Math.min(parseInt(selectorConfig.maxClicks, 10) || 50, 200);

    // "Discard initial elements" support: before any click lands, tag every
    // record-container element that ALREADY exists in the DOM. The engine
    // (with options.discardInitialElements) then drops the tagged elements
    // and keeps only the content the clicks actually loaded. Marking happens
    // here — the page's own JavaScript — because the dashboard only sees the
    // post-click DOM.
    let initialMarked = 0;
    if (selectorConfig.discardInitialElements === true) {
      const initialSelectors = Array.isArray(selectorConfig.initialSelectors)
        ? selectorConfig.initialSelectors
        : [];
      for (const css of initialSelectors) {
        if (!css) continue;
        try {
          document.querySelectorAll(css).forEach((el) => {
            if (!el.hasAttribute('data-ws-initial')) {
              el.setAttribute('data-ws-initial', '1');
              initialMarked++;
            }
          });
        } catch (e) {
          // Invalid container selector — skip it, keep clicking.
        }
      }
    }

    let clickCount = 0;
    const clickedSignatures = new Set();
    // clickMore ends when the page stops growing, NOT when the button node has
    // been seen before (that is the whole point of "click until no more").
    const domSize = () => {
      try { return document.getElementsByTagName('*').length; } catch (e) { return 0; }
    };
    let lastSize = domSize();
    let stableRounds = 0;

    while (clickCount < maxClicks) {
      let visible;
      try {
        visible = Array.from(document.querySelectorAll(clickSelector))
          .filter((b) => b.offsetParent !== null);
      } catch (e) {
        break; // invalid selector — nothing clickable
      }
      if (visible.length === 0) break;

      let targetBtn;
      if (clickType === 'clickOnce') {
        // "Click each button once": walk the candidates and take the first one
        // whose signature has not been clicked yet. The previous code broke
        // out of the loop after the very first click, so only one of N tabs
        // was ever opened.
        targetBtn = visible.find((b) => !clickedSignatures.has(uniquenessSignature(b, uniquenessType)));
        if (!targetBtn) break;
      } else {
        // "Click until no more buttons": the same control is re-clicked on
        // purpose; the growth check below decides when to stop.
        targetBtn = visible[0];
      }
      clickedSignatures.add(uniquenessSignature(targetBtn, uniquenessType));

      targetBtn.scrollIntoView({ behavior: 'smooth', block: 'center' });
      await sleep(100);

      // Dispatch real click events
      targetBtn.dispatchEvent(new MouseEvent('mousedown', { bubbles: true }));
      targetBtn.dispatchEvent(new MouseEvent('mouseup', { bubbles: true }));
      targetBtn.click();

      clickCount++;
      await sleep(clickDelay);

      if (clickType === 'clickOnce') continue;

      const size = domSize();
      if (size <= lastSize) {
        // Nothing new loaded. Require two consecutive stable rounds so a
        // slow response (still in flight) does not end the loop early.
        stableRounds++;
        if (stableRounds >= 2) break;
      } else {
        stableRounds = 0;
      }
      lastSize = size;
    }

    return { clicksDone: clickCount, initialMarked: initialMarked };
  }

  async function handleScrollSelector(selectorConfig) {
    const scrollDelay = selectorConfig.scrollDelay || 1000;
    const maxScrolls = selectorConfig.maxScrolls || 20;
    const scrollSelector = selectorConfig.scrollElementSelector;

    const scrollTarget = scrollSelector ? document.querySelector(scrollSelector) : null;
    let scrollsDone = 0;
    let lastHeight = 0;

    while (scrollsDone < maxScrolls) {
      if (scrollTarget) {
        lastHeight = scrollTarget.scrollHeight;
        scrollTarget.scrollTop = scrollTarget.scrollHeight;
      } else {
        lastHeight = document.documentElement.scrollHeight;
        window.scrollTo(0, document.documentElement.scrollHeight);
      }

      scrollsDone++;
      await sleep(scrollDelay);

      const newHeight = scrollTarget ? scrollTarget.scrollHeight : document.documentElement.scrollHeight;
      if (newHeight <= lastHeight) {
        // No more new content loaded
        break;
      }
    }

    return { scrollsDone: scrollsDone };
  }

  // Listen for execution commands from the dashboard/background. Returning
  // a Promise from the listener is the native Firefox async-response path.
  if (typeof browser !== 'undefined' && browser.runtime && browser.runtime.onMessage) {
    browser.runtime.onMessage.addListener((request) => {
      if (request.type === 'EXECUTE_PAGE_ACTIONS') {
        return (async () => {
          try {
            if (request.actions && request.actions.click) {
              await handleClickSelector(request.actions.click);
            }
            if (request.actions && request.actions.scroll) {
              await handleScrollSelector(request.actions.scroll);
            }
            return { success: true };
          } catch (err) {
            return { success: false, error: err.message };
          }
        })();
      }
    });
  }
})();
