/* AUTO-GENERATED by tools/build_tor.js — Firefox/Tor native (browser.*) build. Do not edit directly. */
/**
 * Storage Engine for Web Scraper.
 * Uses browser.storage.local (Firefox/Tor native promise API) with IndexedDB and localStorage fallbacks.
 */
(function (root, factory) {
  const result = factory();
  if (typeof define === 'function' && define.amd) {
    define([], () => result);
  } else if (typeof module === 'object' && module.exports) {
    module.exports = result;
  }
  if (root) root.AppStorage = result;
  if (typeof window !== 'undefined') window.AppStorage = result;
  if (typeof globalThis !== 'undefined') globalThis.AppStorage = result;
}(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  const DB_NAME = 'WebScraperDB';
  const DB_VERSION = 1;
  const STORE_SITEMAPS = 'sitemaps';
  const STORE_DATA = 'scraped_data';

  const SAMPLE_SITEMAPS = [
    {
      _id: 'sample_ecommerce_products',
      name: 'Sample E-Commerce Store',
      startUrl: ['https://webscraper.io/test-sites/e-commerce/allinone'],
      selectors: [
        {
          id: 'category_link',
          parentSelectors: ['_root'],
          type: 'SelectorLink',
          selector: 'div.sidebar a.nav-link',
          multiple: true,
          linkType: 'linkFromHref',
          delay: 0
        },
        {
          id: 'product_card',
          parentSelectors: ['category_link', '_root'],
          type: 'SelectorElement',
          selector: 'div.product-wrapper',
          multiple: true,
          delay: 0
        },
        {
          id: 'title',
          parentSelectors: ['product_card'],
          type: 'SelectorText',
          selector: 'a.title',
          multiple: false,
          regex: '',
          delay: 0
        },
        {
          id: 'price',
          parentSelectors: ['product_card'],
          type: 'SelectorText',
          selector: 'span.price',
          multiple: false,
          regex: '',
          delay: 0
        },
        {
          id: 'description',
          parentSelectors: ['product_card'],
          type: 'SelectorText',
          selector: 'p.description',
          multiple: false,
          regex: '',
          delay: 0
        },
        {
          id: 'product_image',
          parentSelectors: ['product_card'],
          type: 'SelectorImage',
          selector: 'img.img-fluid',
          multiple: false,
          delay: 0
        }
      ]
    },
    {
      _id: 'sample_data_tables',
      name: 'Sample Tables Scraper',
      startUrl: ['https://webscraper.io/test-sites/tables'],
      selectors: [
        {
          id: 'table_data',
          parentSelectors: ['_root'],
          type: 'SelectorTable',
          selector: 'table.table',
          multiple: true,
          tableHeaderRowSelector: 'thead tr',
          tableDataRowSelector: 'tbody tr',
          columns: [
            { header: '#', name: 'id', extract: true },
            { header: 'First Name', name: 'first_name', extract: true },
            { header: 'Last Name', name: 'last_name', extract: true },
            { header: 'Username', name: 'username', extract: true }
          ],
          delay: 0
        }
      ]
    }
  ];

  class AppStorage {
    constructor() {
      this.db = null;
      this.isExtensionStorage = typeof browser !== 'undefined' && Boolean(browser.storage && browser.storage.local);
      this.initPromise = this.init();
    }

    async init() {
      if (this.isExtensionStorage) {
        try {
          const sitemaps = await this._rawGetAllSitemapsExtension();
          if (sitemaps.length === 0) {
            for (const s of SAMPLE_SITEMAPS) {
              await this._rawSaveSitemapExtension(s);
            }
          }
        } catch (e) {
          console.warn('Extension storage init warning:', e);
        }
        return true;
      }

      if (typeof indexedDB !== 'undefined') {
        return new Promise((resolve) => {
          try {
            const request = indexedDB.open(DB_NAME, DB_VERSION);

            request.onupgradeneeded = (event) => {
              const db = event.target.result;
              if (!db.objectStoreNames.contains(STORE_SITEMAPS)) {
                db.createObjectStore(STORE_SITEMAPS, { keyPath: '_id' });
              }
              if (!db.objectStoreNames.contains(STORE_DATA)) {
                db.createObjectStore(STORE_DATA, { keyPath: 'sitemapId' });
              }
            };

            request.onsuccess = async (event) => {
              this.db = event.target.result;
              try {
                const existing = await this._rawGetAllSitemapsIDB();
                if (existing.length === 0) {
                  for (const s of SAMPLE_SITEMAPS) {
                    await this._rawSaveSitemapIDB(s);
                  }
                }
              } catch (e) {}
              resolve(this.db);
            };

            request.onerror = () => resolve(null);
          } catch (e) {
            resolve(null);
          }
        });
      }

      if (typeof localStorage !== 'undefined') {
        try {
          const list = this._rawGetAllSitemapsLocalStorage();
          if (list.length === 0) {
            for (const s of SAMPLE_SITEMAPS) {
              this._rawSaveSitemapLocalStorage(s);
            }
          }
        } catch (e) {}
      }
      return true;
    }

    // --- RAW INTERNAL STORAGE HELPERS (NO PROMISE AWAIT CYCLE) ---

    async _rawGetAllSitemapsExtension() {
      try {
        const all = await browser.storage.local.get(null);
        if (!all) return [];
        const sitemaps = [];
        for (const k of Object.keys(all)) {
          if (k.startsWith('sitemap_') && all[k]) {
            sitemaps.push(all[k]);
          }
        }
        return sitemaps;
      } catch (e) {
        return [];
      }
    }

    async _rawSaveSitemapExtension(sitemap) {
      try {
        const data = typeof sitemap.toJSON === 'function' ? sitemap.toJSON() : Object.assign({}, sitemap);
        if (!data._id) return null;
        data.name = data.name || data._id;
        data.updatedAt = data.updatedAt || new Date().toISOString();
        const key = `sitemap_${data._id}`;
        try {
          await browser.storage.local.set({ [key]: data });
        } catch (err) {
          console.warn('browser.storage save warning:', err && err.message);
        }
        return data;
      } catch (e) {
        return null;
      }
    }

    _rawGetAllSitemapsIDB() {
      return new Promise((resolve) => {
        if (!this.db) {
          resolve([]);
          return;
        }
        try {
          const tx = this.db.transaction([STORE_SITEMAPS], 'readonly');
          const store = tx.objectStore(STORE_SITEMAPS);
          const req = store.getAll();
          req.onsuccess = () => resolve(req.result || []);
          req.onerror = () => resolve([]);
        } catch (e) {
          resolve([]);
        }
      });
    }

    _rawSaveSitemapIDB(sitemap) {
      return new Promise((resolve) => {
        if (!this.db) {
          resolve(null);
          return;
        }
        try {
          const data = typeof sitemap.toJSON === 'function' ? sitemap.toJSON() : Object.assign({}, sitemap);
          if (!data._id) {
            resolve(null);
            return;
          }
          data.name = data.name || data._id;
          data.updatedAt = data.updatedAt || new Date().toISOString();
          const tx = this.db.transaction([STORE_SITEMAPS], 'readwrite');
          const store = tx.objectStore(STORE_SITEMAPS);
          const req = store.put(data);
          req.onsuccess = () => resolve(data);
          req.onerror = () => resolve(data);
        } catch (e) {
          resolve(null);
        }
      });
    }

    _rawGetAllSitemapsLocalStorage() {
      const list = [];
      if (typeof localStorage !== 'undefined') {
        for (let i = 0; i < localStorage.length; i++) {
          const key = localStorage.key(i);
          if (key && key.startsWith('ws_sitemap_')) {
            try {
              list.push(JSON.parse(localStorage.getItem(key)));
            } catch (e) {}
          }
        }
      }
      return list;
    }

    _rawSaveSitemapLocalStorage(sitemap) {
      const data = typeof sitemap.toJSON === 'function' ? sitemap.toJSON() : Object.assign({}, sitemap);
      if (!data._id) return null;
      data.name = data.name || data._id;
      data.updatedAt = data.updatedAt || new Date().toISOString();
      if (typeof localStorage !== 'undefined') {
        try {
          localStorage.setItem(`ws_sitemap_${data._id}`, JSON.stringify(data));
        } catch (e) {}
      }
      return data;
    }

    // --- PUBLIC ASYNC METHODS ---

    async saveSitemap(sitemap) {
      await this.initPromise;
      const data = typeof sitemap.toJSON === 'function' ? sitemap.toJSON() : Object.assign({}, sitemap);
      if (!data._id) throw new Error('Sitemap must have an _id property.');

      data.name = data.name || data._id;
      data.updatedAt = new Date().toISOString();

      if (this.isExtensionStorage) {
        return this._rawSaveSitemapExtension(data);
      }

      if (this.db) {
        return this._rawSaveSitemapIDB(data);
      }

      return this._rawSaveSitemapLocalStorage(data);
    }

    async getSitemap(sitemapId) {
      await this.initPromise;
      if (!sitemapId) return null;

      if (this.isExtensionStorage) {
        try {
          const res = await browser.storage.local.get(`sitemap_${sitemapId}`);
          return (res && res[`sitemap_${sitemapId}`]) || null;
        } catch (e) {
          return null;
        }
      }

      if (this.db) {
        return new Promise((resolve) => {
          try {
            const tx = this.db.transaction([STORE_SITEMAPS], 'readonly');
            const store = tx.objectStore(STORE_SITEMAPS);
            const req = store.get(sitemapId);
            req.onsuccess = () => resolve(req.result || null);
            req.onerror = () => resolve(null);
          } catch (e) {
            resolve(null);
          }
        });
      }

      if (typeof localStorage !== 'undefined') {
        try {
          const item = localStorage.getItem(`ws_sitemap_${sitemapId}`);
          return item ? JSON.parse(item) : null;
        } catch (e) {
          console.warn('Corrupt sitemap entry in localStorage:', e);
          return null;
        }
      }
      return null;
    }

    async getAllSitemaps() {
      await this.initPromise;

      if (this.isExtensionStorage) {
        return this._rawGetAllSitemapsExtension();
      }

      if (this.db) {
        return this._rawGetAllSitemapsIDB();
      }

      return this._rawGetAllSitemapsLocalStorage();
    }

    async deleteSitemap(sitemapId) {
      await this.initPromise;
      if (!sitemapId) return true;

      if (this.isExtensionStorage) {
        try {
          await browser.storage.local.remove([`sitemap_${sitemapId}`, `data_${sitemapId}`]);
        } catch (e) { /* already gone */ }
        return true;
      }

      if (this.db) {
        await new Promise((resolve) => {
          try {
            const tx = this.db.transaction([STORE_SITEMAPS, STORE_DATA], 'readwrite');
            tx.objectStore(STORE_SITEMAPS).delete(sitemapId);
            tx.objectStore(STORE_DATA).delete(sitemapId);
            tx.oncomplete = () => resolve();
            tx.onerror = () => resolve();
          } catch (e) {
            resolve();
          }
        });
        return true;
      }

      if (typeof localStorage !== 'undefined') {
        localStorage.removeItem(`ws_sitemap_${sitemapId}`);
        localStorage.removeItem(`ws_data_${sitemapId}`);
      }
      return true;
    }

    // Ö8 — user sitemap templates (small payloads; extension storage or localStorage)

    async loadSitemapTemplates() {
      await this.initPromise;
      if (this.isExtensionStorage) {
        try {
          const res = await browser.storage.local.get('sitemap_templates');
          return (res && Array.isArray(res.sitemap_templates)) ? res.sitemap_templates : [];
        } catch (e) {
          return [];
        }
      }
      if (typeof localStorage !== 'undefined') {
        try {
          const raw = localStorage.getItem('sitemap_templates');
          const parsed = raw ? JSON.parse(raw) : [];
          return Array.isArray(parsed) ? parsed : [];
        } catch (e) {
          return [];
        }
      }
      return [];
    }

    async saveSitemapTemplate(template) {
      const list = await this.loadSitemapTemplates();
      const idx = list.findIndex((t) => t && t.id === template.id);
      if (idx >= 0) list[idx] = template;
      else list.push(template);
      if (this.isExtensionStorage) {
        await browser.storage.local.set({ sitemap_templates: list });
        return true;
      }
      if (typeof localStorage !== 'undefined') {
        localStorage.setItem('sitemap_templates', JSON.stringify(list));
      }
      return true;
    }

    async deleteSitemapTemplate(templateId) {
      const list = await this.loadSitemapTemplates();
      const next = list.filter((t) => t && t.id !== templateId);
      if (this.isExtensionStorage) {
        await browser.storage.local.set({ sitemap_templates: next });
        return true;
      }
      if (typeof localStorage !== 'undefined') {
        localStorage.setItem('sitemap_templates', JSON.stringify(next));
      }
      return true;
    }

    async saveScrapedData(sitemapId, records) {
      await this.initPromise;
      const entry = {
        sitemapId: sitemapId,
        scrapedAt: new Date().toISOString(),
        count: Array.isArray(records) ? records.length : 0,
        records: Array.isArray(records) ? records : []
      };

      if (this.isExtensionStorage) {
        try {
          await browser.storage.local.set({ [`data_${sitemapId}`]: entry });
        } catch (e) { /* quota or shutdown */ }
        return entry;
      }

      if (this.db) {
        return new Promise((resolve) => {
          try {
            const tx = this.db.transaction([STORE_DATA], 'readwrite');
            const req = tx.objectStore(STORE_DATA).put(entry);
            req.onsuccess = () => resolve(entry);
            req.onerror = () => resolve(entry);
          } catch (e) {
            resolve(entry);
          }
        });
      }

      if (typeof localStorage !== 'undefined') {
        try {
          localStorage.setItem(`ws_data_${sitemapId}`, JSON.stringify(entry));
        } catch (e) {}
      }
      return entry;
    }

    async getScrapedData(sitemapId) {
      await this.initPromise;
      if (!sitemapId) return [];

      if (this.isExtensionStorage) {
        try {
          const res = await browser.storage.local.get(`data_${sitemapId}`);
          const entry = res && res[`data_${sitemapId}`];
          return (entry && Array.isArray(entry.records)) ? entry.records : [];
        } catch (e) {
          return [];
        }
      }

      if (this.db) {
        return new Promise((resolve) => {
          try {
            const tx = this.db.transaction([STORE_DATA], 'readonly');
            const req = tx.objectStore(STORE_DATA).get(sitemapId);
            req.onsuccess = () => {
              const res = req.result;
              resolve((res && Array.isArray(res.records)) ? res.records : []);
            };
            req.onerror = () => resolve([]);
          } catch (e) {
            resolve([]);
          }
        });
      }

      if (typeof localStorage !== 'undefined') {
        const raw = localStorage.getItem(`ws_data_${sitemapId}`);
        if (raw) {
          try {
            const parsed = JSON.parse(raw);
            return parsed.records || [];
          } catch (e) {}
        }
      }
      return [];
    }

    async clearScrapedData(sitemapId) {
      await this.initPromise;
      if (!sitemapId) return true;

      if (this.isExtensionStorage) {
        try {
          await browser.storage.local.remove(`data_${sitemapId}`);
        } catch (e) { /* already gone */ }
        return true;
      }

      if (this.db) {
        return new Promise((resolve) => {
          try {
            const tx = this.db.transaction([STORE_DATA], 'readwrite');
            const req = tx.objectStore(STORE_DATA).delete(sitemapId);
            req.onsuccess = () => resolve(true);
            req.onerror = () => resolve(true);
          } catch (e) {
            resolve(true);
          }
        });
      }

      if (typeof localStorage !== 'undefined') {
        localStorage.removeItem(`ws_data_${sitemapId}`);
      }
      return true;
    }
  }

  return new AppStorage();
}));
