/* AUTO-GENERATED by tools/build_tor.js — Firefox/Tor native (browser.*) build. Do not edit directly. */
/**
 * Export Manager for Scraped Data and Sitemaps.
 * Pure Vanilla JS, zero external dependencies.
 */
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    define(['../../lib/csv.js', '../../lib/xlsx.js', '../../lib/transforms.js'], factory);
  } else if (typeof module === 'object' && module.exports) {
    const CSV = require('../../lib/csv.js');
    const XLSX = require('../../lib/xlsx.js');
    const TextTransforms = require('../../lib/transforms.js');
    module.exports = factory(CSV, XLSX, TextTransforms);
  } else {
    root.Exporter = factory(root.CSV, root.XLSX, root.TextTransforms);
  }
}(typeof self !== 'undefined' ? self : this, function (CSV, XLSX, TextTransforms) {
  'use strict';

  function sanitizeFilename(name) {
    return String(name || 'data')
      .replace(/[^a-zA-Z0-9_.-]/g, '_')
      .replace(/_{2,}/g, '_');
  }

  function downloadBlob(blob, filename) {
    if (typeof window === 'undefined') return;

    const url = URL.createObjectURL(blob);
    
    // Use the browser.downloads promise API when available (Firefox/Tor)
    if (typeof browser !== 'undefined' && browser.downloads && browser.downloads.download) {
      browser.downloads.download({
        url: url,
        filename: filename,
        saveAs: true
      }).catch(() => { /* user cancelled the save dialog */ })
        .then(() => {
          setTimeout(() => URL.revokeObjectURL(url), 10000);
        });
      return;
    }

    // DOM Anchor download
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 5000);
  }

  class Exporter {
    /**
     * Converts records to CSV string.
     */
    // P2.4 — per-column CSV types (persisted on the sitemap):
    //   number : normalize localized numbers ("1.234,56", "$1,234.56")
    //   date   : format Date-like values with the column's date format
    //
    // Number parsing DELEGATES to lib/transforms.js so the whole codebase has
    // exactly one parser. This class used to carry its own copy with different
    // heuristics, which made the same cell mean two different things: a
    // `number` transform read "1,234" as 1.234 while a CSV export read it as
    // 1234 (1000x off), and "1.234.567" was rejected by one and accepted by
    // the other. transforms.js is a tiny pure module with no DOM dependency
    // and is already loaded before this file in dashboard.html / panel.html.

    /**
     * Parses localized numbers; returns a JS number or null.
     * Thin wrapper kept for API stability (tests, callers) over the single
     * canonical implementation in lib/transforms.js.
     */
    static parseColumnNumber(raw) {
      if (TextTransforms && typeof TextTransforms.parseNumber === 'function') {
        return TextTransforms.parseNumber(raw);
      }
      // Defensive fallback for an embedding that loaded Exporter without the
      // transform pipeline: integers and plain decimals only, never a wrong
      // localized guess.
      if (typeof raw === 'number') return Number.isFinite(raw) ? raw : null;
      if (raw === null || raw === undefined) return null;
      const s = String(raw).trim();
      if (!/^[+-]?\d+(\.\d+)?$/.test(s)) return null;
      const n = Number(s);
      return Number.isFinite(n) ? n : null;
    }

    /** Formats Date-like values (Date, ISO string, number) for CSV output. */
    static formatColumnDate(value, format) {
      const fmt = typeof format === 'string' && format ? format : 'YYYY-MM-DD';
      let d = value;
      if (!(d instanceof Date)) {
        d = (typeof value === 'number' || (typeof value === 'string' && /^\d{10,13}$/.test(value.trim())))
          ? new Date(/^\d{13}$/.test(String(value).trim()) ? Number(value) : Number(value) * 1000)
          : new Date(value);
      }
      if (!(d instanceof Date) || isNaN(d.getTime())) return value; // not a date: leave untouched
      const p2 = (n) => String(n).padStart(2, '0');
      const tokens = {
        YYYY: String(d.getFullYear()),
        MM: p2(d.getMonth() + 1),
        DD: p2(d.getDate()),
        HH: p2(d.getHours()),
        mm: p2(d.getMinutes()),
        ss: p2(d.getSeconds())
      };
      return fmt
        .replace(/YYYY/g, tokens.YYYY)
        .replace(/MM/g, tokens.MM)
        .replace(/DD/g, tokens.DD)
        .replace(/HH/g, tokens.HH)
        .replace(/mm/g, tokens.mm)
        .replace(/ss/g, tokens.ss);
    }

    /** Applies one column's persisted type to a cell value. */
    static formatCellValue(value, colCfg) {
      if (!colCfg || !colCfg.type) return value;
      if (colCfg.type === 'number') {
        const n = this.parseColumnNumber(value);
        return n === null ? value : n;
      }
      if (colCfg.type === 'date') {
        return this.formatColumnDate(value, colCfg.format);
      }
      return value;
    }

    static toCSV(data, options = {}) {
      const opts = Object.assign({
        delimiter: ',',
        bom: true,
        header: true
      }, options);

      // P2.4: apply the persisted per-column types before serializing.
      // columnTypes may be an array of {name, type, format} (the sitemap
      // shape) or a map of name -> cfg.
      let byName = null;
      if (options.columnTypes) {
        byName = new Map();
        if (Array.isArray(options.columnTypes)) {
          for (const ct of options.columnTypes) {
            if (ct && ct.name) byName.set(ct.name, ct);
          }
        } else if (typeof options.columnTypes === 'object') {
          for (const k of Object.keys(options.columnTypes)) byName.set(k, options.columnTypes[k]);
        }
        if (Array.isArray(data)) {
          data = data.map((row) => {
            if (!row || typeof row !== 'object') return row;
            const out = {};
            for (const key of Object.keys(row)) {
              out[key] = this.formatCellValue(row[key], byName.get(key) || null);
            }
            return out;
          });
        }
      }

      return CSV.unparse(data, opts);
    }

    /**
     * Converts records to Excel XML string.
     */
    static toExcel(data, sheetName) {
      return XLSX.generateExcelXml(data, sheetName);
    }

    /**
     * Converts data to formatted JSON string.
     */
    static toJSON(data, pretty = true) {
      return JSON.stringify(data, null, pretty ? 2 : 0);
    }

    /**
     * Converts records to TSV (tab separated values) string.
     */
    static toTSV(data, options = {}) {
      return this.toCSV(data, Object.assign({ delimiter: '\t' }, options));
    }

    /**
     * Converts records to NDJSON / JSON Lines: one JSON object per line.
     */
    static toNDJSON(data) {
      if (!Array.isArray(data) || data.length === 0) return '';
      return data.map(row => JSON.stringify(row)).join('\n') + '\n';
    }

    /**
     * Downloads scraped data as CSV file.
     */
    static downloadCSV(data, sitemapName, delimiter = ',', columnTypes) {
      const csvStr = this.toCSV(data, { delimiter: delimiter, bom: true, columnTypes: columnTypes });
      const blob = new Blob([csvStr], { type: 'text/csv;charset=utf-8;' });
      const filename = `${sanitizeFilename(sitemapName)}_data.csv`;
      downloadBlob(blob, filename);
    }

    /**
     * Downloads scraped data as Excel XLSX/XML file.
     */
    static downloadExcel(data, sitemapName) {
      const xmlStr = this.toExcel(data, sitemapName);
      const blob = new Blob([xmlStr], { type: 'application/vnd.ms-excel;charset=utf-8;' });
      const filename = `${sanitizeFilename(sitemapName)}_data.xls`;
      downloadBlob(blob, filename);
    }

    /**
     * Ö6: downloads a real Office Open XML workbook (.xlsx).
     */
    static async downloadXLSX(data, sitemapName) {
      const bytes = await XLSX.generateXlsx(data, sitemapName);
      const blob = new Blob([bytes], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
      const filename = `${sanitizeFilename(sitemapName)}_data.xlsx`;
      downloadBlob(blob, filename);
    }

    /**
     * Ö6: rich HTML table markup (for clipboard pasting into spreadsheets).
     */
    static buildHtmlTable(data) {
      return XLSX.buildHtmlTable(data);
    }

    /**
     * Downloads scraped data as JSON file.
     */
    static downloadJSON(data, sitemapName) {
      const jsonStr = this.toJSON(data, true);
      const blob = new Blob([jsonStr], { type: 'application/json;charset=utf-8;' });
      const filename = `${sanitizeFilename(sitemapName)}_data.json`;
      downloadBlob(blob, filename);
    }

    /**
     * Downloads scraped data as TSV file.
     */
    static downloadTSV(data, sitemapName) {
      const tsvStr = this.toTSV(data, { bom: true });
      const blob = new Blob([tsvStr], { type: 'text/tab-separated-values;charset=utf-8;' });
      const filename = `${sanitizeFilename(sitemapName)}_data.tsv`;
      downloadBlob(blob, filename);
    }

    /**
     * Downloads scraped data as NDJSON (JSON Lines) file.
     */
    static downloadNDJSON(data, sitemapName) {
      const ndStr = this.toNDJSON(data);
      const blob = new Blob([ndStr], { type: 'application/x-ndjson;charset=utf-8;' });
      const filename = `${sanitizeFilename(sitemapName)}_data.ndjson`;
      downloadBlob(blob, filename);
    }

    // P3.9 — Markdown + XML exports and the meta.json bundle.

    /** Union of record keys, in first-seen order. */
    static recordFields(data) {
      const fields = [];
      const seen = new Set();
      for (const row of Array.isArray(data) ? data : []) {
        if (!row || typeof row !== 'object') continue;
        for (const key of Object.keys(row)) {
          if (!seen.has(key)) { seen.add(key); fields.push(key); }
        }
      }
      return fields;
    }

    /** Converts records to a GitHub-flavored Markdown table. */
    static toMarkdown(data, title) {
      const rows = Array.isArray(data) ? data : [];
      const esc = (v) => String(v === undefined || v === null ? '' : v)
        .replace(/\|/g, '\\|').replace(/\r?\n/g, '<br>');
      let out = '';
      if (title) out += `# ${String(title).replace(/\|/g, '\\|')}\n\n`;
      if (rows.length === 0) {
        return out + '_No records._\n';
      }
      const fields = this.recordFields(rows);
      out += `| ${fields.map((f) => esc(f)).join(' | ')} |\n`;
      out += `| ${fields.map(() => '---').join(' | ')} |\n`;
      for (const row of rows) {
        out += `| ${fields.map((f) => esc(row ? row[f] : '')).join(' | ')} |\n`;
      }
      return out;
    }

    /** Converts records to a simple, well-formed XML document. */
    static toXML(data, rootName) {
      const root = String(rootName || 'scrapedData').replace(/[^A-Za-z0-9_]/g, '') || 'scrapedData';
      const tag = (name) => {
        const clean = String(name).replace(/[^A-Za-z0-9_.]/g, '_');
        return /^[A-Za-z_]/.test(clean) ? clean : 'f_' + clean;
      };
      const esc = (v) => String(v === undefined || v === null ? '' : v)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/\r?\n/g, ' ');
      const rows = Array.isArray(data) ? data : [];
      // Hoisted OUT of the row loop: recordFields() walks every row and every
      // key to build the union, so calling it per row made XML export
      // quadratic (measured: 500 rows = 29 ms, 1000 = 75 ms, 2000 = 313 ms —
      // ~8 s for 10k rows) while producing exactly the same output.
      const fields = this.recordFields(rows);
      let out = `<?xml version="1.0" encoding="UTF-8"?>\n<${root} count="${rows.length}">\n`;
      for (const row of rows) {
        out += '  <record>\n';
        for (const f of fields) {
          const t = tag(f);
          out += `    <${t}>${esc(row ? row[f] : '')}</${t}>\n`;
        }
        out += '  </record>\n';
      }
      out += `</${root}>\n`;
      return out;
    }

    /**
     * Meta document describing a data export — written into the ZIP bundle
     * (meta.json) and reused by tests.
     */
    static buildMeta(sitemap, data) {
      const rows = Array.isArray(data) ? data : [];
      return {
        generator: 'Web-Scrape dashboard (chrome-edge)',
        generatorVersion: '1.0.0',
        sitemapId: sitemap && sitemap._id ? sitemap._id : (sitemap && sitemap.id) || null,
        sitemapName: sitemap && sitemap.name ? sitemap.name : null,
        sourceUrls: sitemap && Array.isArray(sitemap.startUrl) ? sitemap.startUrl.slice() : [],
        exportedAt: new Date().toISOString(),
        recordCount: rows.length,
        columns: this.recordFields(rows),
        columnTypes: sitemap && Array.isArray(sitemap.columnTypes)
          ? sitemap.columnTypes.map((ct) => Object.assign({}, ct))
          : []
      };
    }

    static downloadMarkdown(data, sitemapName) {
      const md = this.toMarkdown(data, sitemapName);
      const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
      downloadBlob(blob, `${sanitizeFilename(sitemapName)}_data.md`);
    }

    static downloadXML(data, sitemapName) {
      const xml = this.toXML(data);
      const blob = new Blob([xml], { type: 'application/xml;charset=utf-8;' });
      downloadBlob(blob, `${sanitizeFilename(sitemapName)}_data.xml`);
    }

    /**
     * Builds a backup object containing every sitemap definition.
     */
    static buildSitemapsBackup(sitemaps) {
      return {
        format: 'web-scraper-backup',
        version: 1,
        exportedAt: new Date().toISOString(),
        sitemaps: Array.isArray(sitemaps) ? sitemaps : []
      };
    }

    /**
     * Downloads all sitemaps in a single backup JSON file.
     */
    static downloadAllSitemaps(sitemaps) {
      const backup = this.buildSitemapsBackup(sitemaps);
      const jsonStr = this.toJSON(backup, true);
      const blob = new Blob([jsonStr], { type: 'application/json;charset=utf-8;' });
      const date = new Date().toISOString().slice(0, 10);
      downloadBlob(blob, `webscraper_backup_${date}.json`);
    }

    /**
     * Downloads Sitemap definition as JSON file.
     */
    static downloadSitemapJSON(sitemapData, sitemapName) {
      const jsonStr = this.toJSON(sitemapData, true);
      const blob = new Blob([jsonStr], { type: 'application/json;charset=utf-8;' });
      const filename = `sitemap_${sanitizeFilename(sitemapName || sitemapData._id)}.json`;
      downloadBlob(blob, filename);
    }
  }

  return Exporter;
}));
