/* AUTO-GENERATED by tools/build_tor.js — Firefox/Tor native (browser.*) build. Do not edit directly. */
/**
 * Export Manager for Scraped Data and Sitemaps.
 * Pure Vanilla JS, zero external dependencies.
 */
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    define(['../../lib/csv.js', '../../lib/xlsx.js'], factory);
  } else if (typeof module === 'object' && module.exports) {
    const CSV = require('../../lib/csv.js');
    const XLSX = require('../../lib/xlsx.js');
    module.exports = factory(CSV, XLSX);
  } else {
    root.Exporter = factory(root.CSV, root.XLSX);
  }
}(typeof self !== 'undefined' ? self : this, function (CSV, XLSX) {
  'use strict';

  function sanitizeFilename(name) {
    return String(name || 'data')
      .replace(/[^a-zA-Z0-9_\-\.]/g, '_')
      .replace(/_{2,}/g, '_');
  }

  function downloadBlob(blob, filename) {
    if (typeof window === 'undefined') return;

    const url = URL.createObjectURL(blob);
    
    // Use the browser.downloads promise API when available (Firefox/Tor)
    if (typeof browser !== 'undefined' && browser.downloads && browser.downloads.download) {
      browser.downloads.download({
        url: url,
        filename: filename,
        saveAs: true
      }).catch(() => { /* user cancelled the save dialog */ })
        .then(() => {
          setTimeout(() => URL.revokeObjectURL(url), 10000);
        });
      return;
    }

    // DOM Anchor download
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 5000);
  }

  class Exporter {
    /**
     * Converts records to CSV string.
     */
    static toCSV(data, options = {}) {
      const opts = Object.assign({
        delimiter: ',',
        bom: true,
        header: true
      }, options);

      return CSV.unparse(data, opts);
    }

    /**
     * Converts records to Excel XML string.
     */
    static toExcel(data, sheetName) {
      return XLSX.generateExcelXml(data, sheetName);
    }

    /**
     * Converts data to formatted JSON string.
     */
    static toJSON(data, pretty = true) {
      return JSON.stringify(data, null, pretty ? 2 : 0);
    }

    /**
     * Converts records to TSV (tab separated values) string.
     */
    static toTSV(data, options = {}) {
      return this.toCSV(data, Object.assign({ delimiter: '\t' }, options));
    }

    /**
     * Converts records to NDJSON / JSON Lines: one JSON object per line.
     */
    static toNDJSON(data) {
      if (!Array.isArray(data) || data.length === 0) return '';
      return data.map(row => JSON.stringify(row)).join('\n') + '\n';
    }

    /**
     * Downloads scraped data as CSV file.
     */
    static downloadCSV(data, sitemapName, delimiter = ',') {
      const csvStr = this.toCSV(data, { delimiter: delimiter, bom: true });
      const blob = new Blob([csvStr], { type: 'text/csv;charset=utf-8;' });
      const filename = `${sanitizeFilename(sitemapName)}_data.csv`;
      downloadBlob(blob, filename);
    }

    /**
     * Downloads scraped data as Excel XLSX/XML file.
     */
    static downloadExcel(data, sitemapName) {
      const xmlStr = this.toExcel(data, sitemapName);
      const blob = new Blob([xmlStr], { type: 'application/vnd.ms-excel;charset=utf-8;' });
      const filename = `${sanitizeFilename(sitemapName)}_data.xls`;
      downloadBlob(blob, filename);
    }

    /**
     * Ö6: downloads a real Office Open XML workbook (.xlsx).
     */
    static async downloadXLSX(data, sitemapName) {
      const bytes = await XLSX.generateXlsx(data, sitemapName);
      const blob = new Blob([bytes], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
      const filename = `${sanitizeFilename(sitemapName)}_data.xlsx`;
      downloadBlob(blob, filename);
    }

    /**
     * Ö6: rich HTML table markup (for clipboard pasting into spreadsheets).
     */
    static buildHtmlTable(data) {
      return XLSX.buildHtmlTable(data);
    }

    /**
     * Downloads scraped data as JSON file.
     */
    static downloadJSON(data, sitemapName) {
      const jsonStr = this.toJSON(data, true);
      const blob = new Blob([jsonStr], { type: 'application/json;charset=utf-8;' });
      const filename = `${sanitizeFilename(sitemapName)}_data.json`;
      downloadBlob(blob, filename);
    }

    /**
     * Downloads scraped data as TSV file.
     */
    static downloadTSV(data, sitemapName) {
      const tsvStr = this.toTSV(data, { bom: true });
      const blob = new Blob([tsvStr], { type: 'text/tab-separated-values;charset=utf-8;' });
      const filename = `${sanitizeFilename(sitemapName)}_data.tsv`;
      downloadBlob(blob, filename);
    }

    /**
     * Downloads scraped data as NDJSON (JSON Lines) file.
     */
    static downloadNDJSON(data, sitemapName) {
      const ndStr = this.toNDJSON(data);
      const blob = new Blob([ndStr], { type: 'application/x-ndjson;charset=utf-8;' });
      const filename = `${sanitizeFilename(sitemapName)}_data.ndjson`;
      downloadBlob(blob, filename);
    }

    /**
     * Builds a backup object containing every sitemap definition.
     */
    static buildSitemapsBackup(sitemaps) {
      return {
        format: 'web-scraper-backup',
        version: 1,
        exportedAt: new Date().toISOString(),
        sitemaps: Array.isArray(sitemaps) ? sitemaps : []
      };
    }

    /**
     * Downloads all sitemaps in a single backup JSON file.
     */
    static downloadAllSitemaps(sitemaps) {
      const backup = this.buildSitemapsBackup(sitemaps);
      const jsonStr = this.toJSON(backup, true);
      const blob = new Blob([jsonStr], { type: 'application/json;charset=utf-8;' });
      const date = new Date().toISOString().slice(0, 10);
      downloadBlob(blob, `webscraper_backup_${date}.json`);
    }

    /**
     * Downloads Sitemap definition as JSON file.
     */
    static downloadSitemapJSON(sitemapData, sitemapName) {
      const jsonStr = this.toJSON(sitemapData, true);
      const blob = new Blob([jsonStr], { type: 'application/json;charset=utf-8;' });
      const filename = `sitemap_${sanitizeFilename(sitemapName || sitemapData._id)}.json`;
      downloadBlob(blob, filename);
    }
  }

  return Exporter;
}));
