#!/usr/bin/env node
/**
 * Generates the Tor Browser (Firefox ESR) NATIVE build in tor/ from the
 * Chrome/Edge source tree in chrome-edge/.
 *
 * The tor/ build targets ONLY Firefox/Tor: it uses the promise-based
 * `browser.*` WebExtension namespace with async/await instead of the
 * callback-style `chrome.*` API. The output must contain no chrome.* API
 * calls at all (validated at build time).
 *
 * How each file is produced:
 *
 *   1. manifest.json          – transformed (event page, options_ui, gecko id)
 *   2. background.js          – full native replacement (tools/tor_native/)
 *   3. devtools/devtools.js   – full native replacement (tools/tor_native/)
 *   4. popup/popup.js         – full native replacement (tools/tor_native/)
 *   5. dashboard/dashboard.js – targeted section rewrites (picker + tab
 *                               runner become async browser.* code)
 *   6. src/storage/Storage.js – chrome.storage callback blocks become
 *                               awaited browser.storage.local calls
 *   7. src/export/Exporter.js – browser.downloads promise API
 *   8. content/*.js           – browser.runtime messaging (promise replies)
 *   9. lib/i18n.js            – "chrome://" wording becomes "about:"
 *   10. everything else        – copied verbatim (engines, models, lib,
 *                               locales, icons, css, html)
 *
 * Every rewrite anchors on an exact source excerpt and THROWS when the
 * anchor is missing, so `npm run check:tor` fails loudly if the
 * chrome-edge/ sources drift instead of silently shipping stale Firefox code.
 *
 * Usage:  node tools/build_tor.js          (writes the tor/ tree)
 *         node tools/build_tor.js --check  (verifies it is up to date)
 */
'use strict';

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
// Chrome/Edge source tree (tests and tooling stay at the repository root).
const SRC = path.join(ROOT, 'chrome-edge');
const TARGET = path.join(ROOT, 'tor');
const NATIVE = path.join(__dirname, 'tor_native');

const GECKO_ID = 'web-scraper@webbhesap.github.io';
const GECKO_MIN_VERSION = '115.0'; // Tor Browser 13+ is based on Firefox ESR 115+

// Directories and files copied from the repository root (some entries are
// then transformed or replaced, see TRANSFORMS / NATIVE_REPLACEMENTS).
const COPY_DIRS = ['_locales', 'content', 'dashboard', 'devtools', 'icons', 'lib', 'popup', 'src'];
const COPY_FILES = ['index.html'];

const BANNER = '/* AUTO-GENERATED by tools/build_tor.js — Firefox/Tor native (browser.*) build. Do not edit directly. */\n';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Replaces the first exact occurrence of `from`; throws when missing. */
function replaceExact(source, from, to, label) {
  const idx = source.indexOf(from);
  if (idx === -1) {
    throw new Error(`build_tor: anchor not found (${label}). The root source changed — update tools/build_tor.js.`);
  }
  return source.slice(0, idx) + to + source.slice(idx + from.length);
}

/**
 * Replaces everything from `startMarker` (inclusive) up to `endMarker`
 * (exclusive) with `replacement`; throws when either marker is missing.
 */
function replaceSection(source, startMarker, endMarker, replacement, label) {
  const s = source.indexOf(startMarker);
  if (s === -1) {
    throw new Error(`build_tor: section start not found (${label}). Update tools/build_tor.js.`);
  }
  const e = source.indexOf(endMarker, s);
  if (e === -1) {
    throw new Error(`build_tor: section end not found (${label}). Update tools/build_tor.js.`);
  }
  return source.slice(0, s) + replacement + source.slice(e);
}

function readNative(name) {
  return fs.readFileSync(path.join(NATIVE, name), 'utf8');
}

// ---------------------------------------------------------------------------
// manifest.json
// ---------------------------------------------------------------------------

function buildManifest(sourceJson) {
  const manifest = JSON.parse(sourceJson);

  // 1. Background: Firefox MV3 has no service workers — use an event page.
  //    Storage.js must load first because the native background.js expects
  //    AppStorage to be available.
  manifest.background = {
    scripts: ['src/storage/Storage.js', 'background.js']
  };

  // 2. options_page is Chrome-only; Firefox requires options_ui.
  if (manifest.options_page) {
    manifest.options_ui = {
      page: manifest.options_page,
      open_in_tab: true
    };
    delete manifest.options_page;
  }

  // 3. Firefox requires an explicit add-on id for unsigned/sideloaded MV3.
  manifest.browser_specific_settings = {
    gecko: {
      id: GECKO_ID,
      strict_min_version: GECKO_MIN_VERSION
    }
  };

  return JSON.stringify(manifest, null, 2) + '\n';
}

// ---------------------------------------------------------------------------
// dashboard/dashboard.js
// ---------------------------------------------------------------------------

function transformDashboardJs(source) {
  let out = source;

  // 1. Picker-result listener: browser.* namespace.
  out = replaceExact(
    out,
    "if (typeof chrome !== 'undefined' && chrome.runtime && chrome.runtime.onMessage) {\n      chrome.runtime.onMessage.addListener((message) => {",
    "if (typeof browser !== 'undefined' && browser.runtime && browser.runtime.onMessage) {\n      browser.runtime.onMessage.addListener((message) => {",
    'dashboard picker-result listener'
  );

  // 2. getTargetTabId + ensureHostPermission + launchElementPicker become
  //    native async browser.* implementations.
  out = replaceSection(
    out,
    '  function getTargetTabId(callback) {',
    '    // Standalone fallback: simulate picker dialog prompt',
    readNative(path.join('snippets', 'dashboard_picker_native.js')),
    'dashboard picker section'
  );

  // 3. startScraping permission gate: ensureHostPermission is async now.
  out = replaceExact(
    out,
    'const permitted = await new Promise((resolve) => ensureHostPermission(resolve));',
    'const permitted = await ensureHostPermission();',
    'dashboard startScraping permission gate'
  );

  // 4. Tab runner: async browser.tabs / browser.scripting implementation.
  out = replaceSection(
    out,
    '  function createTabOrFetchRunner() {',
    '    // Default fetch & DOMParser fallback',
    readNative(path.join('snippets', 'dashboard_runner_native.js')),
    'dashboard tab runner section'
  );

  return BANNER + out;
}

// ---------------------------------------------------------------------------
// src/storage/Storage.js
// ---------------------------------------------------------------------------

function transformStorageJs(source) {
  let out = source;

  out = replaceExact(
    out,
    ' * Uses chrome.storage.local for synchronized extension storage with IndexedDB and localStorage fallbacks.',
    ' * Uses browser.storage.local (Firefox/Tor native promise API) with IndexedDB and localStorage fallbacks.',
    'storage header comment'
  );

  out = replaceExact(
    out,
    "this.isChromeStorage = typeof chrome !== 'undefined' && Boolean(chrome.storage && chrome.storage.local);",
    "this.isChromeStorage = typeof browser !== 'undefined' && Boolean(browser.storage && browser.storage.local);",
    'storage detection'
  );

  out = replaceExact(
    out,
    `    _rawGetAllSitemapsChrome() {
      return new Promise((resolve) => {
        try {
          chrome.storage.local.get(null, (all) => {
            if ((chrome.runtime && chrome.runtime.lastError) || !all) {
              resolve([]);
              return;
            }
            const sitemaps = [];
            for (const k of Object.keys(all)) {
              if (k.startsWith('sitemap_') && all[k]) {
                sitemaps.push(all[k]);
              }
            }
            resolve(sitemaps);
          });
        } catch (e) {
          resolve([]);
        }
      });
    }`,
    `    async _rawGetAllSitemapsChrome() {
      try {
        const all = await browser.storage.local.get(null);
        if (!all) return [];
        const sitemaps = [];
        for (const k of Object.keys(all)) {
          if (k.startsWith('sitemap_') && all[k]) {
            sitemaps.push(all[k]);
          }
        }
        return sitemaps;
      } catch (e) {
        return [];
      }
    }`,
    'storage _rawGetAllSitemaps'
  );

  out = replaceExact(
    out,
    `    _rawSaveSitemapChrome(sitemap) {
      return new Promise((resolve) => {
        try {
          const data = typeof sitemap.toJSON === 'function' ? sitemap.toJSON() : Object.assign({}, sitemap);
          if (!data._id) {
            resolve(null);
            return;
          }
          data.name = data.name || data._id;
          data.updatedAt = data.updatedAt || new Date().toISOString();
          const key = \`sitemap_\${data._id}\`;
          chrome.storage.local.set({ [key]: data }, () => {
            if (chrome.runtime && chrome.runtime.lastError) {
              console.warn('chrome.storage save warning:', chrome.runtime.lastError.message);
            }
            resolve(data);
          });
        } catch (e) {
          resolve(null);
        }
      });
    }`,
    `    async _rawSaveSitemapChrome(sitemap) {
      try {
        const data = typeof sitemap.toJSON === 'function' ? sitemap.toJSON() : Object.assign({}, sitemap);
        if (!data._id) return null;
        data.name = data.name || data._id;
        data.updatedAt = data.updatedAt || new Date().toISOString();
        const key = \`sitemap_\${data._id}\`;
        try {
          await browser.storage.local.set({ [key]: data });
        } catch (err) {
          console.warn('browser.storage save warning:', err && err.message);
        }
        return data;
      } catch (e) {
        return null;
      }
    }`,
    'storage _rawSaveSitemap'
  );

  out = replaceExact(
    out,
    `      if (this.isChromeStorage) {
        return new Promise((resolve) => {
          chrome.storage.local.get(\`sitemap_\${sitemapId}\`, (res) => {
            if ((chrome.runtime && chrome.runtime.lastError) || !res) {
              resolve(null);
              return;
            }
            resolve(res[\`sitemap_\${sitemapId}\`] || null);
          });
        });
      }`,
    `      if (this.isChromeStorage) {
        try {
          const res = await browser.storage.local.get(\`sitemap_\${sitemapId}\`);
          return (res && res[\`sitemap_\${sitemapId}\`]) || null;
        } catch (e) {
          return null;
        }
      }`,
    'storage getSitemap'
  );

  out = replaceExact(
    out,
    `      if (this.isChromeStorage) {
        return new Promise((resolve) => {
          chrome.storage.local.remove([\`sitemap_\${sitemapId}\`, \`data_\${sitemapId}\`], () => {
            resolve(true);
          });
        });
      }`,
    `      if (this.isChromeStorage) {
        try {
          await browser.storage.local.remove([\`sitemap_\${sitemapId}\`, \`data_\${sitemapId}\`]);
        } catch (e) { /* already gone */ }
        return true;
      }`,
    'storage deleteSitemap'
  );

  out = replaceExact(
    out,
    `      if (this.isChromeStorage) {
        return new Promise((resolve) => {
          chrome.storage.local.set({ [\`data_\${sitemapId}\`]: entry }, () => {
            resolve(entry);
          });
        });
      }`,
    `      if (this.isChromeStorage) {
        try {
          await browser.storage.local.set({ [\`data_\${sitemapId}\`]: entry });
        } catch (e) { /* quota or shutdown */ }
        return entry;
      }`,
    'storage saveScrapedData'
  );

  out = replaceExact(
    out,
    `      if (this.isChromeStorage) {
        return new Promise((resolve) => {
          chrome.storage.local.get(\`data_\${sitemapId}\`, (res) => {
            if ((chrome.runtime && chrome.runtime.lastError) || !res) {
              resolve([]);
              return;
            }
            const entry = res[\`data_\${sitemapId}\`];
            resolve((entry && Array.isArray(entry.records)) ? entry.records : []);
          });
        });
      }`,
    `      if (this.isChromeStorage) {
        try {
          const res = await browser.storage.local.get(\`data_\${sitemapId}\`);
          const entry = res && res[\`data_\${sitemapId}\`];
          return (entry && Array.isArray(entry.records)) ? entry.records : [];
        } catch (e) {
          return [];
        }
      }`,
    'storage getScrapedData'
  );

  out = replaceExact(
    out,
    `      if (this.isChromeStorage) {
        return new Promise((resolve) => {
          chrome.storage.local.remove(\`data_\${sitemapId}\`, () => {
            resolve(true);
          });
        });
      }`,
    `      if (this.isChromeStorage) {
        try {
          await browser.storage.local.remove(\`data_\${sitemapId}\`);
        } catch (e) { /* already gone */ }
        return true;
      }`,
    'storage clearScrapedData'
  );

  out = replaceExact(
    out,
    "console.warn('Chrome storage init warning:', e);",
    "console.warn('Extension storage init warning:', e);",
    'storage init warning'
  );

  // Ö8 — sitemap template persistence (chrome callback -> browser promise)

  out = replaceExact(
    out,
    `      if (this.isChromeStorage) {
        return new Promise((resolve) => {
          chrome.storage.local.get('sitemap_templates', (res) => {
            resolve((res && Array.isArray(res.sitemap_templates)) ? res.sitemap_templates : []);
          });
        });
      }`,
    `      if (this.isChromeStorage) {
        try {
          const res = await browser.storage.local.get('sitemap_templates');
          return (res && Array.isArray(res.sitemap_templates)) ? res.sitemap_templates : [];
        } catch (e) {
          return [];
        }
      }`,
    'storage loadSitemapTemplates'
  );

  out = replaceExact(
    out,
    `      if (this.isChromeStorage) {
        return new Promise((resolve) => {
          chrome.storage.local.set({ sitemap_templates: list }, () => resolve(true));
        });
      }`,
    `      if (this.isChromeStorage) {
        await browser.storage.local.set({ sitemap_templates: list });
        return true;
      }`,
    'storage saveSitemapTemplate'
  );

  out = replaceExact(
    out,
    `      if (this.isChromeStorage) {
        return new Promise((resolve) => {
          chrome.storage.local.set({ sitemap_templates: next }, () => resolve(true));
        });
      }`,
    `      if (this.isChromeStorage) {
        await browser.storage.local.set({ sitemap_templates: next });
        return true;
      }`,
    'storage deleteSitemapTemplate'
  );
  // Property/method names say "Chrome" but the Tor build only talks to
  // browser.storage — rename them so the native code reads honestly.
  out = out
    .split('isChromeStorage').join('isExtensionStorage')
    .split('_rawGetAllSitemapsChrome').join('_rawGetAllSitemapsExtension')
    .split('_rawSaveSitemapChrome').join('_rawSaveSitemapExtension');

  return BANNER + out;
}

// ---------------------------------------------------------------------------
// src/export/Exporter.js
// ---------------------------------------------------------------------------

function transformExporterJs(source) {
  const out = replaceExact(
    source,
    `    // Check if chrome.downloads API is available
    if (typeof chrome !== 'undefined' && chrome.downloads && chrome.downloads.download) {
      chrome.downloads.download({
        url: url,
        filename: filename,
        saveAs: true
      }, () => {
        setTimeout(() => URL.revokeObjectURL(url), 10000);
      });
      return;
    }`,
    `    // Use the browser.downloads promise API when available (Firefox/Tor)
    if (typeof browser !== 'undefined' && browser.downloads && browser.downloads.download) {
      browser.downloads.download({
        url: url,
        filename: filename,
        saveAs: true
      }).catch(() => { /* user cancelled the save dialog */ })
        .then(() => {
          setTimeout(() => URL.revokeObjectURL(url), 10000);
        });
      return;
    }`,
    'exporter downloads'
  );
  return BANNER + out;
}

// ---------------------------------------------------------------------------
// content/selector_picker.js
// ---------------------------------------------------------------------------

function transformSelectorPickerJs(source) {
  let out = source;

  out = replaceExact(
    out,
    `    // Send result to background / extension
    if (typeof chrome !== 'undefined' && chrome.runtime && chrome.runtime.sendMessage) {
      chrome.runtime.sendMessage({
        type: 'PICKER_RESULT',
        selector: selectorResult,
        multiple: multipleResult
      });
    }`,
    `    // Send result to background / extension
    if (typeof browser !== 'undefined' && browser.runtime && browser.runtime.sendMessage) {
      browser.runtime.sendMessage({
        type: 'PICKER_RESULT',
        selector: selectorResult,
        multiple: multipleResult
      }).catch(() => { /* no open extension views */ });
    }`,
    'picker result message'
  );

  out = replaceExact(
    out,
    `    if (typeof chrome !== 'undefined' && chrome.runtime && chrome.runtime.sendMessage) {
      chrome.runtime.sendMessage({ type: 'PICKER_CANCELLED' });
    }`,
    `    if (typeof browser !== 'undefined' && browser.runtime && browser.runtime.sendMessage) {
      browser.runtime.sendMessage({ type: 'PICKER_CANCELLED' }).catch(() => { /* no open extension views */ });
    }`,
    'picker cancel message'
  );

  out = replaceExact(
    out,
    `  // Listen for messages from background/devtools
  if (typeof chrome !== 'undefined' && chrome.runtime && chrome.runtime.onMessage) {
    chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
      if (!request || typeof request.type !== 'string') return;
      if (request.type === 'START_PICKER') {
        startPicker(request);
        sendResponse({ success: true });
      } else if (request.type === 'STOP_PICKER') {
        stopPicker();
        sendResponse({ success: true });
      } else if (request.type === 'ELEMENT_PREVIEW') {
        if (!isActive) startPicker(request);
        currentSelector = request.selector || currentSelector;
        updateHighlights();
        let count = 0;
        count = queryInScope(currentSelector).length;
        sendResponse({ count: count });
      } else if (request.type === 'DATA_PREVIEW') {
        if (!isActive) startPicker(request);
        currentSelector = request.selector || currentSelector;
        showDataPreview();
        sendResponse({ success: true });
      }
      return true;
    });
  }`,
    `  // Listen for messages from background/devtools. Returning a Promise is
  // the native Firefox way to deliver the response.
  if (typeof browser !== 'undefined' && browser.runtime && browser.runtime.onMessage) {
    browser.runtime.onMessage.addListener((request) => {
      if (request.type === 'START_PICKER') {
        startPicker(request);
        return Promise.resolve({ success: true });
      } else if (request.type === 'STOP_PICKER') {
        stopPicker();
        return Promise.resolve({ success: true });
      } else if (request.type === 'ELEMENT_PREVIEW') {
        if (!isActive) startPicker(request);
        currentSelector = request.selector || currentSelector;
        updateHighlights();
        const count = queryInScope(currentSelector).length;
        return Promise.resolve({ count: count });
      } else if (request.type === 'DATA_PREVIEW') {
        if (!isActive) startPicker(request);
        currentSelector = request.selector || currentSelector;
        showDataPreview();
        return Promise.resolve({ success: true });
      }
    });
  }`,
    'picker message listener'
  );

  return BANNER + out;
}

// ---------------------------------------------------------------------------
// content/scraper_content.js
// ---------------------------------------------------------------------------

function transformScraperContentJs(source) {
  const out = replaceExact(
    source,
    `  // Listen for execution commands from background script
  if (typeof chrome !== 'undefined' && chrome.runtime && chrome.runtime.onMessage) {
    chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
      if (request.type === 'EXECUTE_PAGE_ACTIONS') {
        (async () => {
          try {
            if (request.actions && request.actions.click) {
              await handleClickSelector(request.actions.click);
            }
            if (request.actions && request.actions.scroll) {
              await handleScrollSelector(request.actions.scroll);
            }
            sendResponse({ success: true });
          } catch (err) {
            sendResponse({ success: false, error: err.message });
          }
        })();
        return true; // Keep message channel open for async response
      }
    });
  }`,
    `  // Listen for execution commands from the dashboard/background. Returning
  // a Promise from the listener is the native Firefox async-response path.
  if (typeof browser !== 'undefined' && browser.runtime && browser.runtime.onMessage) {
    browser.runtime.onMessage.addListener((request) => {
      if (request.type === 'EXECUTE_PAGE_ACTIONS') {
        return (async () => {
          try {
            if (request.actions && request.actions.click) {
              await handleClickSelector(request.actions.click);
            }
            if (request.actions && request.actions.scroll) {
              await handleScrollSelector(request.actions.scroll);
            }
            return { success: true };
          } catch (err) {
            return { success: false, error: err.message };
          }
        })();
      }
    });
  }`,
    'scraper content listener'
  );
  return BANNER + out;
}

// ---------------------------------------------------------------------------
// lib/i18n.js — user-facing wording only (chrome:// pages -> about: pages)
// ---------------------------------------------------------------------------

function transformI18nJs(source) {
  return source.split('(chrome://)').join('(about:)');
}

// ---------------------------------------------------------------------------
// README
// ---------------------------------------------------------------------------

function buildReadme() {
  return `# Web Scraper — Tor Browser Build (Firefox native)

This folder contains the **Tor Browser (Firefox ESR) native** build of the
extension. It is **auto-generated** from the Chrome/Edge source tree in
\`chrome-edge/\` by \`tools/build_tor.js\` — do not edit files here directly.
Make changes in the \`chrome-edge/\` tree (or in \`tools/tor_native/\` for the
Firefox-specific files), then run:

\`\`\`bash
npm run build:tor
\`\`\`

## Firefox-native, not a compatibility shim

Unlike a straight copy of the Chrome code, this build targets **only**
Firefox/Tor and uses the idiomatic WebExtension style throughout:

- the promise-based \`browser.*\` namespace (no \`chrome.*\` anywhere — the
  build fails if a \`chrome.\` API call slips in),
- \`async\`/\`await\` instead of callback pyramids + \`runtime.lastError\`,
- message listeners answer by returning a Promise,
- a background **event page** (\`background.scripts\`) instead of a service
  worker, and \`options_ui\` instead of \`options_page\`,
- \`browser_specific_settings.gecko\` add-on id for sideloading.

| Area | Chrome/Edge (root) | Tor/Firefox (this folder) |
|------|--------------------|---------------------------|
| API namespace | callback-style \`chrome.*\` | promise-based \`browser.*\` + async/await |
| Background | \`service_worker\` | \`background.scripts\` event page (Storage.js + background.js) |
| Options | \`options_page\` | \`options_ui\` (open in tab) |
| Add-on identity | — | \`browser_specific_settings.gecko\` id |
| Engines / UI / locales | identical | identical |

## Installing in Tor Browser

### Temporary (for testing — removed when the browser closes)
1. Open \`about:debugging#/runtime/this-firefox\`.
2. Click **Load Temporary Add-on…**.
3. Select \`tor/manifest.json\`.

### Permanent
Firefox normally requires signed add-ons. In Tor Browser (ESR based) you can
allow unsigned installs:
1. Open \`about:config\` and set \`xpinstall.signatures.required\` to \`false\`.
2. Zip the **contents** of this folder (manifest.json at the zip root), rename
   the file to \`web-scraper.xpi\`.
3. Open \`about:addons\` → gear icon → **Install Add-on From File…** and pick
   the \`.xpi\`.

### Host permissions
Firefox MV3 does **not** grant \`<all_urls>\` automatically. After installing,
open the add-on's **Permissions** tab in \`about:addons\` and enable
*"Access your data for all websites"*, otherwise the picker and the scraper
cannot reach pages.

## Troubleshooting

**Toolbar button / DevTools tab is missing entirely**
Tor Browser runs in permanent private-browsing mode, and Firefox does not run
newly installed extensions in private windows by default. Open
\`about:addons\` → Web Scraper → set **Run in Private Windows** to **Allow**,
then reopen your tabs. To pin the button, click the puzzle-piece (🧩) icon in
the toolbar → gear next to Web Scraper → **Pin to Toolbar**. The DevTools tab
only registers when DevTools is (re)opened after the extension is running.

**"Missing host permission for the tab"**
Firefox MV3 treats host permissions as opt-in. The extension checks this at
runtime and shows the browser's own permission prompt the first time you use
the picker or start a scrape — accept it there, or enable *"Access your data
for all websites"* under \`about:addons\` → Web Scraper → Permissions. Tabs
opened *before* the grant may need a reload.

## Privacy warning

The Tor Project recommends **against** installing extra extensions: every
add-on makes your browser fingerprint more unique, and automated background
tab crawling is clearly distinguishable from normal Tor traffic. Expect slow
crawls, exit-node CAPTCHAs and site blocks. Use this build only if you accept
those trade-offs.
`;
}

// ---------------------------------------------------------------------------
// Tree assembly
// ---------------------------------------------------------------------------

// Files fully replaced by hand-written Firefox-native implementations.
const NATIVE_REPLACEMENTS = {
  'background.js': 'background.js',
  'devtools/devtools.js': 'devtools.js',
  'popup/popup.js': 'popup.js'
};

// Files rewritten from the root source via anchored transformations.
const TRANSFORMS = {
  'dashboard/dashboard.js': transformDashboardJs,
  'src/storage/Storage.js': transformStorageJs,
  'src/export/Exporter.js': transformExporterJs,
  'content/selector_picker.js': transformSelectorPickerJs,
  'content/scraper_content.js': transformScraperContentJs,
  'lib/i18n.js': transformI18nJs
};

/** Recursively lists files under dir, returning paths relative to dir. */
function listFiles(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...listFiles(full).map((p) => path.join(entry.name, p)));
    } else {
      out.push(entry.name);
    }
  }
  return out;
}

/**
 * Ensures no chrome.* API call survives in the generated JS. Identifiers
 * that merely start with "chrome" (chromeEl, chromeHideTimer), string
 * literals such as 'chrome://' and prose like "slideshow chrome. The"
 * do not match the tight `chrome.<ident>` pattern.
 */
function assertNoChromeApi(files) {
  const offenders = [];
  for (const [rel, content] of files) {
    if (!rel.endsWith('.js')) continue;
    const text = content.toString('utf8');
    const match = text.match(/(?<![A-Za-z0-9_$])chrome\.[A-Za-z_$]/);
    if (match) offenders.push(rel);
  }
  if (offenders.length) {
    throw new Error('build_tor: chrome.* API leaked into the native build: ' + offenders.join(', '));
  }
}

/** Computes the full { relativePath: Buffer } map for the tor/ tree. */
function buildTree() {
  const files = new Map();

  files.set('manifest.json', Buffer.from(buildManifest(fs.readFileSync(path.join(SRC, 'manifest.json'), 'utf8'))));
  files.set('README.md', Buffer.from(buildReadme()));

  for (const rel of COPY_FILES) {
    files.set(rel, fs.readFileSync(path.join(SRC, rel)));
  }
  for (const dir of COPY_DIRS) {
    for (const rel of listFiles(path.join(SRC, dir))) {
      const key = path.join(dir, rel);
      files.set(key, fs.readFileSync(path.join(SRC, key)));
    }
  }

  for (const [rel, nativeName] of Object.entries(NATIVE_REPLACEMENTS)) {
    files.set(rel, Buffer.from(readNative(nativeName)));
  }
  for (const [rel, transform] of Object.entries(TRANSFORMS)) {
    const source = fs.readFileSync(path.join(SRC, rel), 'utf8');
    files.set(rel, Buffer.from(transform(source)));
  }

  assertNoChromeApi(files);
  return files;
}

function main() {
  const check = process.argv.includes('--check');
  const tree = buildTree();

  if (check) {
    const problems = [];
    for (const [rel, content] of tree) {
      const dest = path.join(TARGET, rel);
      if (!fs.existsSync(dest)) {
        problems.push(`missing: tor/${rel}`);
      } else if (!fs.readFileSync(dest).equals(content)) {
        problems.push(`stale:   tor/${rel}`);
      }
    }
    // Detect orphan files left behind after renames/deletions in the source.
    if (fs.existsSync(TARGET)) {
      for (const rel of listFiles(TARGET)) {
        if (!tree.has(rel)) problems.push(`orphan:  tor/${rel}`);
      }
    }
    if (problems.length) {
      console.error('tor/ build is out of date. Run: npm run build:tor');
      problems.forEach((p) => console.error('  ' + p));
      process.exit(1);
    }
    console.log('tor/ build is up to date.');
    return;
  }

  // Clean rebuild so removed source files never linger in the output.
  fs.rmSync(TARGET, { recursive: true, force: true });
  for (const [rel, content] of tree) {
    const dest = path.join(TARGET, rel);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, content);
  }
  console.log(`Wrote ${tree.size} files to ${path.relative(ROOT, TARGET)}/`);
}

if (require.main === module) main();

module.exports = {
  buildManifest,
  buildTree,
  transformDashboardJs,
  transformStorageJs,
  TARGET,
  GECKO_ID
};
