#!/usr/bin/env node
/**
 * Generates the Tor Browser (Firefox ESR) compatible build in tor/ from the
 * Chrome/Edge source tree.
 *
 * The extension is pure Vanilla JS and uses the callback-style chrome.* API,
 * which Firefox supports natively, so almost everything is copied verbatim.
 * Only browser-level differences are transformed:
 *
 *   1. manifest.json
 *      - `background.service_worker` -> `background.scripts` (Firefox MV3
 *        runs background event pages, not service workers). Storage.js is
 *        listed before background.js because importScripts() does not exist
 *        in a background page.
 *      - `options_page` -> `options_ui` (Firefox only supports options_ui).
 *      - adds `browser_specific_settings.gecko` (required id + min version).
 *   2. background.js
 *      - the importScripts(...) call is removed; the same file is loaded via
 *        the manifest `background.scripts` array instead.
 *
 * Everything else (dashboard, devtools, popup, content scripts, engines,
 * lib, locales, icons) is byte-for-byte identical to the Chrome build.
 *
 * Usage:  node tools/build_tor.js          (writes the tor/ tree)
 *         node tools/build_tor.js --check  (verifies it is up to date)
 */
'use strict';

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const TARGET = path.join(ROOT, 'tor');

const GECKO_ID = 'web-scraper@webbhesap.github.io';
const GECKO_MIN_VERSION = '115.0'; // Tor Browser 13+ is based on Firefox ESR 115+

// Directories and files copied verbatim from the repository root.
const COPY_DIRS = ['_locales', 'content', 'dashboard', 'devtools', 'icons', 'lib', 'popup', 'src'];
const COPY_FILES = ['index.html'];

function buildManifest(sourceJson) {
  const manifest = JSON.parse(sourceJson);

  // 1. Background: Firefox MV3 has no service workers — use an event page.
  //    Storage.js must load first because background.js has no importScripts.
  manifest.background = {
    scripts: ['src/storage/Storage.js', 'background.js']
  };

  // 2. options_page is Chrome-only; Firefox requires options_ui.
  if (manifest.options_page) {
    manifest.options_ui = {
      page: manifest.options_page,
      open_in_tab: true
    };
    delete manifest.options_page;
  }

  // 3. Firefox requires an explicit add-on id for unsigned/sideloaded MV3.
  manifest.browser_specific_settings = {
    gecko: {
      id: GECKO_ID,
      strict_min_version: GECKO_MIN_VERSION
    }
  };

  return JSON.stringify(manifest, null, 2) + '\n';
}

function buildBackgroundJs(source) {
  // Remove the importScripts(...) statement — dependencies are loaded via the
  // manifest background.scripts array in the Firefox build.
  const transformed = source.replace(
    /importScripts\s*\([\s\S]*?\)\s*;\s*\n/,
    '// NOTE (Tor/Firefox build): dependencies such as src/storage/Storage.js are\n' +
    '// loaded through manifest.json "background.scripts". Worker-style script\n' +
    '// imports are unavailable because Firefox runs the background as an event\n' +
    '// page, not a service worker.\n'
  );
  return '/* AUTO-GENERATED by tools/build_tor.js from background.js. Do not edit directly. */\n' + transformed;
}

function buildReadme() {
  return `# Web Scraper — Tor Browser Build

This folder contains the **Tor Browser (Firefox ESR) compatible** build of the
extension. It is **auto-generated** from the Chrome/Edge source tree at the
repository root by \`tools/build_tor.js\` — do not edit files here directly.
Make changes in the root tree, then run:

\`\`\`bash
npm run build:tor
\`\`\`

## Differences from the Chrome build

| Area | Chrome/Edge (root) | Tor/Firefox (this folder) |
|------|--------------------|---------------------------|
| Background | \`service_worker\` | \`background.scripts\` event page (Storage.js + background.js) |
| Options | \`options_page\` | \`options_ui\` (open in tab) |
| Add-on identity | — | \`browser_specific_settings.gecko\` id |
| Everything else | identical | identical |

## Installing in Tor Browser

### Temporary (for testing — removed when the browser closes)
1. Open \`about:debugging#/runtime/this-firefox\`.
2. Click **Load Temporary Add-on…**.
3. Select \`tor/manifest.json\`.

### Permanent
Firefox normally requires signed add-ons. In Tor Browser (ESR based) you can
allow unsigned installs:
1. Open \`about:config\` and set \`xpinstall.signatures.required\` to \`false\`.
2. Zip the **contents** of this folder (manifest.json at the zip root), rename
   the file to \`web-scraper.xpi\`.
3. Open \`about:addons\` → gear icon → **Install Add-on From File…** and pick
   the \`.xpi\`.

### Host permissions
Firefox MV3 does **not** grant \`<all_urls>\` automatically. After installing,
open the add-on's **Permissions** tab in \`about:addons\` and enable
*"Access your data for all websites"*, otherwise the picker and the scraper
cannot reach pages.

## Privacy warning

The Tor Project recommends **against** installing extra extensions: every
add-on makes your browser fingerprint more unique, and automated background
tab crawling is clearly distinguishable from normal Tor traffic. Expect slow
crawls, exit-node CAPTCHAs and site blocks. Use this build only if you accept
those trade-offs.
`;
}

/** Recursively lists files under dir, returning paths relative to dir. */
function listFiles(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...listFiles(full).map((p) => path.join(entry.name, p)));
    } else {
      out.push(entry.name);
    }
  }
  return out;
}

/** Computes the full { relativePath: Buffer } map for the tor/ tree. */
function buildTree() {
  const files = new Map();

  files.set('manifest.json', Buffer.from(buildManifest(fs.readFileSync(path.join(ROOT, 'manifest.json'), 'utf8'))));
  files.set('background.js', Buffer.from(buildBackgroundJs(fs.readFileSync(path.join(ROOT, 'background.js'), 'utf8'))));
  files.set('README.md', Buffer.from(buildReadme()));

  for (const rel of COPY_FILES) {
    files.set(rel, fs.readFileSync(path.join(ROOT, rel)));
  }
  for (const dir of COPY_DIRS) {
    for (const rel of listFiles(path.join(ROOT, dir))) {
      const key = path.join(dir, rel);
      files.set(key, fs.readFileSync(path.join(ROOT, key)));
    }
  }
  return files;
}

function main() {
  const check = process.argv.includes('--check');
  const tree = buildTree();

  if (check) {
    const problems = [];
    for (const [rel, content] of tree) {
      const dest = path.join(TARGET, rel);
      if (!fs.existsSync(dest)) {
        problems.push(`missing: tor/${rel}`);
      } else if (!fs.readFileSync(dest).equals(content)) {
        problems.push(`stale:   tor/${rel}`);
      }
    }
    // Detect orphan files left behind after renames/deletions in the source.
    if (fs.existsSync(TARGET)) {
      for (const rel of listFiles(TARGET)) {
        if (!tree.has(rel)) problems.push(`orphan:  tor/${rel}`);
      }
    }
    if (problems.length) {
      console.error('tor/ build is out of date. Run: npm run build:tor');
      problems.forEach((p) => console.error('  ' + p));
      process.exit(1);
    }
    console.log('tor/ build is up to date.');
    return;
  }

  // Clean rebuild so removed source files never linger in the output.
  fs.rmSync(TARGET, { recursive: true, force: true });
  for (const [rel, content] of tree) {
    const dest = path.join(TARGET, rel);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, content);
  }
  console.log(`Wrote ${tree.size} files to ${path.relative(ROOT, TARGET)}/`);
}

if (require.main === module) main();

module.exports = { buildManifest, buildBackgroundJs, buildTree, TARGET, GECKO_ID };
